Repository hi-java-docs/Java-Specifications-Docs, pull requests merged in 2019-12, with the labels that each got.

#62 zh and en
  zh_en/java_se_8/jvm/0-preface-to-the-javase8-edition.md
  zh_en/java_se_8/jvm/1.1-a-bit-of-history.md
  zh_en/java_se_8/jvm/1.2-the-java-virtual-machine.md
  zh_en/java_se_8/jvm/1.3-organization-of-the-specification.md
  zh_en/java_se_8/jvm/1.4-notation.md
  zh_en/java_se_8/jvm/1.5-feedback.md
  zh_en/java_se_8/jvm/2.0-the-structure-of-the-java-virtual-machine.md
  zh_en/java_se_8/jvm/2.1-the-class-file-format.md
  zh_en/java_se_8/jvm/2.10-exceptions.md
  zh_en/java_se_8/jvm/2.11-instruction-set-summary.md
  zh_en/java_se_8/jvm/2.11.1-types-and-the-java-virtual-machine.md
  zh_en/java_se_8/jvm/2.11.10-synchronization.md
  zh_en/java_se_8/jvm/2.11.2-local-and-store-instructions.md
  zh_en/java_se_8/jvm/2.11.3-arithmetic-instructions.md
  zh_en/java_se_8/jvm/2.11.4-type-conversion-instructions.md
  zh_en/java_se_8/jvm/2.11.5-object-creation-and-manipulation.md
  zh_en/java_se_8/jvm/2.11.6-operand-stack-management-instructions.md
  zh_en/java_se_8/jvm/2.11.7-control-transfer-instructions.md
  zh_en/java_se_8/jvm/2.11.8-method-invocation-and-return-instructions.md
  zh_en/java_se_8/jvm/2.11.9-throwing-exceptions.md
  zh_en/java_se_8/jvm/2.12-class-libraries.md
  zh_en/java_se_8/jvm/2.13-public-design-private-implementation.md
  zh_en/java_se_8/jvm/2.2-data-types.md
  zh_en/java_se_8/jvm/2.3-primitive-types-and-values.md
  zh_en/java_se_8/jvm/2.3.1-integral-types-and-values.md
  zh_en/java_se_8/jvm/2.3.2-floating-point-types-value-set-and-values.md
  zh_en/java_se_8/jvm/2.3.3-the-returnaddress-type-and-values.md
  zh_en/java_se_8/jvm/2.3.4-the-boolean-type.md
  zh_en/java_se_8/jvm/2.4-reference-types-and-values.md
  zh_en/java_se_8/jvm/2.5-run-time-data-areas.md
  zh_en/java_se_8/jvm/2.5.1-the-pc-register.md
  zh_en/java_se_8/jvm/2.5.2-java-virtual-machine-stacks.md
  zh_en/java_se_8/jvm/2.5.3-heap.md
  zh_en/java_se_8/jvm/2.5.4-method-area.md
  zh_en/java_se_8/jvm/2.5.5-run-time-constant-pool.md
  zh_en/java_se_8/jvm/2.5.6-native-method-stacks.md
  zh_en/java_se_8/jvm/2.6-frames.md
  zh_en/java_se_8/jvm/2.6.1-local-variables.md
  zh_en/java_se_8/jvm/2.6.2-operand-stacks.md
  zh_en/java_se_8/jvm/2.6.3-dynamic-linking.md
  zh_en/java_se_8/jvm/2.6.4-normal-method-invocation-completion.md
  zh_en/java_se_8/jvm/2.6.5-abrupt-method-invocation-completion.md
  zh_en/java_se_8/jvm/2.7-representation-of-objects.md
  zh_en/java_se_8/jvm/2.8-floating-point-arithmetic.md
  zh_en/java_se_8/jvm/2.8.1-java-virtual-machine-floating-point-arithmetic-and-IEEE-754.md
  zh_en/java_se_8/jvm/2.8.2-floating-point-modes.md
  zh_en/java_se_8/jvm/2.8.3-value-set-conversion.md
  zh_en/java_se_8/jvm/2.9-special-method.md
  zh_en/java_se_8/jvm/jvms8.pdf
  zh_en/java_se_8/jvm/table-of-contents.md
Labels: documentation

#15 zh-translation:zh/java_se_8/jvm/1.1-a-bit-of-history
  en/java_se_8/jvm/1.1-a-bit-of-history.md
  zh/java_se_8/jvm/1.1-a-bit-of-history.md
  zh_en/java_se_8/jvm/1.1-a-bit-of-history.md
Labels: pushed

#66 第三章整理
  en/java_se_8/jvm/3.0-compiling-for-the-Java-Virtual-Machine.md
  en/java_se_8/jvm/3.1-format-of-examples.md
  en/java_se_8/jvm/3.10-compiling-switches.md
  en/java_se_8/jvm/3.11-operations-on-the-operand-stack.md
  en/java_se_8/jvm/3.12-throwing-and-handling-exceptions.md
  en/java_se_8/jvm/3.13-compiling-finally.md
  en/java_se_8/jvm/3.14-synchronization.md
  en/java_se_8/jvm/3.15-annotations.md
  en/java_se_8/jvm/3.2-use-of-constants-local-variables-and-control-constructs.md
  en/java_se_8/jvm/3.3-arithmetic.md
  en/java_se_8/jvm/3.4-accessing-the-run-time-constant-pool.md
  en/java_se_8/jvm/3.5-more-control-examples.md
  en/java_se_8/jvm/3.6-receiving-arguments.md
  en/java_se_8/jvm/3.7-invoking-methods.md
  en/java_se_8/jvm/3.8-working-with-class-instances.md
  en/java_se_8/jvm/3.9-arrays.md
  zh/java_se_8/jvm/3.0-compiling-for-the-java-virtual-machine.md
  zh/java_se_8/jvm/3.1-format-of-examples.md
  zh/java_se_8/jvm/3.10-compiling-switches.md
  zh/java_se_8/jvm/3.11-operations-on-the-operand-stack.md
  zh/java_se_8/jvm/3.12-throwing-and-handling-exceptions.md
  zh/java_se_8/jvm/3.13-compiling-finally.md
  zh/java_se_8/jvm/3.14-synchronization.md
  zh/java_se_8/jvm/3.15-annotations.md
  zh/java_se_8/jvm/3.2-use-of-constants-local-variables-and-control-constructs.md
  zh/java_se_8/jvm/3.3-arithmetic.md
  zh/java_se_8/jvm/3.4-accessing-the-run-time-constant-pool.md
  zh/java_se_8/jvm/3.5-more-control-examples.md
  zh/java_se_8/jvm/3.6-receiving-arguments.md
  zh/java_se_8/jvm/3.7-invoking-methods.md
  zh/java_se_8/jvm/3.8-working-with-class-instances.md
  zh/java_se_8/jvm/3.9-arrays.md
Labels: documentation, enhancement

#65 zh-translation:zh/java_se_8/jvm/2.2-data-types.md
  zh/java_se_8/jvm/2.2-data-types.md
Labels: pushed
